/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGUI;

import Logica.Filme;
import dao.FilmeDao;
import java.awt.Container;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


public class VisualizarTela extends javax.swing.JFrame {
    
   
    private final JLabel imgFundoCad;
    
           
    public VisualizarTela() {
        initComponents();
        
                imgFundoCad = new JLabel(); 
        imgFundoCad.setSize(1024, 768);
        imgFundoCad.setIcon(new ImageIcon("images/fundoVisualizar.jpg"));
        
    	Container pane = this.getContentPane();
        
        pane.add(imgFundoCad);
        
        this.setSize(1024, 768);
        this.setResizable(false);
        this.setLocation(200, 100);
    }
    
        private void mostraPesquisa(List<Filme> filmes) {
            if(filmes.size() == 0){
                JOptionPane.showMessageDialog(null, "Nenhum filme encontrado.");
            }else{
                String[] linha = new String[]{null, null, null, null, null, null, null, null, null, null, null, null, null};
                for (int i = 0; i < filmes.size(); i++){
                    tmFilmes.addRow(linha);
                    tmFilmes.setValueAt(filmes.get(i).getTitulo(), i, 0);
                    tmFilmes.setValueAt(filmes.get(i).getGenero(), i, 1);
                    tmFilmes.setValueAt(filmes.get(i).getPais(), i, 2);
                    tmFilmes.setValueAt(filmes.get(i).getAno_lancamento(), i, 3);
                    tmFilmes.setValueAt(filmes.get(i).getDiretor(), i, 4);
                    tmFilmes.setValueAt(filmes.get(i).getIdioma(), i, 5);
                    tmFilmes.setValueAt(filmes.get(i).getTempo_duracao(), i, 6);
                    tmFilmes.setValueAt(filmes.get(i).getJa_assistiu(), i, 7);
                    tmFilmes.setValueAt(filmes.get(i).getSinopse(), i, 8);
                    tmFilmes.setValueAt(filmes.get(i).getComentario(), i, 9);
                    tmFilmes.setValueAt(filmes.get(i).getTrilha_sonora(), i, 10);
                    tmFilmes.setValueAt(filmes.get(i).getTrailer(), i, 11);   
                    
                    
                }
 
            }
    }
    
    //define modelo da tabela
    DefaultTableModel tmFilmes = new DefaultTableModel(null, new String[]{"Título", "Gênero", "País de origem", "Ano de lançamento", "Diretor", "Idioma", 
    "Tempo de duração", "Assistiu?", "Sinopse", "Comentário", "Trilha sonora", "Trailer"});
    
    List<Filme> filmes;
    ListSelectionModel lsmFilme;

    
    public void listarFilmes() throws SQLException{
        
        FilmeDao dao = new FilmeDao();
        filmes = dao.getLista("%" + CampoPesquisa.getText() + "%");
        mostraPesquisa(filmes);
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonVoltar = new javax.swing.JButton();
        LabelTituloCadastro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFilmes = new javax.swing.JTable();
        CampoPesquisa = new javax.swing.JTextField();
        ButtonPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        LabelTituloCadastro.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        LabelTituloCadastro.setText("Filmes");

        jTFilmes.setModel(tmFilmes);
        jScrollPane1.setViewportView(jTFilmes);

        ButtonPesquisa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ButtonPesquisa.setText("Pesquisar");
        ButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(923, Short.MAX_VALUE)
                        .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPesquisa)
                        .addGap(3, 3, 3)
                        .addComponent(LabelTituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTituloCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed

                   dispose();
              
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisaActionPerformed

        try {
            listarFilmes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problama na pesquisa" + ex);
        }
        
        
    }//GEN-LAST:event_ButtonPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPesquisa;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JTextField CampoPesquisa;
    private javax.swing.JLabel LabelTituloCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFilmes;
    // End of variables declaration//GEN-END:variables


}
